/* Auto-generated — run generate-pdf-catalog.py to refresh */
const PDFS_ARCHIVE_DETAILS = "https://archive.org/details/faisalPDF";
const PDFS_DOWNLOAD_BASE = "https://archive.org/download/faisalPDF/";

const PDF_CATEGORIES = [
  {
    "id": "quran",
    "label": "Quran & Tafsir",
    "order": 1
  },
  {
    "id": "aqeedah",
    "label": "Aqeedah & Refutations",
    "order": 2
  },
  {
    "id": "ummah",
    "label": "Ummah & Politics",
    "order": 3
  },
  {
    "id": "character",
    "label": "Character & Family",
    "order": 4
  },
  {
    "id": "general",
    "label": "General",
    "order": 5
  }
];

const PDFS = [
  {
    "title": "Science Of Quran – Part 1",
    "archive": "shatkh faisal pdfs/Science Of Quran – Part 1.pdf",
    "size": 315948,
    "sizeLabel": "308.5 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%201.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%201.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%201.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "series": "Science Of Quran",
    "part": 1,
    "sortOrder": 0,
    "id": 0,
    "thumb": "thumb/pdfs/753ab1ff324bc145.jpg"
  },
  {
    "title": "Science Of Quran – Part 2 – The Wahy",
    "archive": "shatkh faisal pdfs/Science Of Quran – Part 2 – The Wahy.pdf",
    "size": 136938,
    "sizeLabel": "133.7 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%202%20%E2%80%93%20The%20Wahy.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%202%20%E2%80%93%20The%20Wahy.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Science%20Of%20Quran%20%E2%80%93%20Part%202%20%E2%80%93%20The%20Wahy.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "series": "Science Of Quran",
    "part": 2,
    "sortOrder": 1,
    "id": 1,
    "thumb": "thumb/pdfs/09936b05dc2fe7ac.jpg"
  },
  {
    "title": "Science Of Quran Part 3 The History Of The Quran's Descent",
    "archive": "shatkh faisal pdfs/Science_Of_Quran_Part_3_The_History_Of_The_Quran's_Descent.pdf",
    "size": 159988,
    "sizeLabel": "156.2 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_3_The_History_Of_The_Quran%27s_Descent.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_3_The_History_Of_The_Quran%27s_Descent.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_3_The_History_Of_The_Quran%27s_Descent.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "series": "Science Of Quran",
    "part": 3,
    "sortOrder": 2,
    "id": 2,
    "thumb": "thumb/pdfs/44998012f9f5746b.jpg"
  },
  {
    "title": "Science Of Quran Part 4 The 20 Reasons Why The Quran Is A Wise Book",
    "archive": "shatkh faisal pdfs/Science_Of_Quran_Part_4_The_20_Reasons_Why_The_Quran_Is_A_Wise_Book.pdf",
    "size": 243899,
    "sizeLabel": "238.2 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_4_The_20_Reasons_Why_The_Quran_Is_A_Wise_Book.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_4_The_20_Reasons_Why_The_Quran_Is_A_Wise_Book.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Science_Of_Quran_Part_4_The_20_Reasons_Why_The_Quran_Is_A_Wise_Book.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "series": "Science Of Quran",
    "part": 4,
    "sortOrder": 3,
    "id": 3,
    "thumb": "thumb/pdfs/33fb247bc9817956.jpg"
  },
  {
    "title": "Tafsir Surah Saff",
    "archive": "shatkh faisal pdfs/Tafsir Surah Saff .pdf",
    "size": 473902,
    "sizeLabel": "462.8 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Tafsir%20Surah%20Saff%20.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Tafsir%20Surah%20Saff%20.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Tafsir%20Surah%20Saff%20.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "sortOrder": 4,
    "id": 4,
    "thumb": "thumb/pdfs/92962688dc0e6dc7.jpg"
  },
  {
    "title": "Towards Watering Down The Holy Quran",
    "archive": "shatkh faisal pdfs/Towards Watering Down The Holy Quran.pdf",
    "size": 201037,
    "sizeLabel": "196.3 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Towards%20Watering%20Down%20The%20Holy%20Quran.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Towards%20Watering%20Down%20The%20Holy%20Quran.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Towards%20Watering%20Down%20The%20Holy%20Quran.pdf",
    "category": "quran",
    "categoryLabel": "Quran & Tafsir",
    "sortOrder": 5,
    "id": 5,
    "thumb": "thumb/pdfs/6f0a9be9e02c0719.jpg"
  },
  {
    "title": "Refuting The Lie Concerning Kufr Doona Kufr",
    "archive": "shatkh faisal pdfs/Refuting The Lie Concerning Kufr Doona Kufr.pdf",
    "size": 320215,
    "sizeLabel": "312.7 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20Kufr%20Doona%20Kufr.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20Kufr%20Doona%20Kufr.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20Kufr%20Doona%20Kufr.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "series": "Refuting The Lie",
    "part": 1,
    "sortOrder": 6,
    "id": 6,
    "thumb": "thumb/pdfs/e5ed75c78c05f31a.jpg"
  },
  {
    "title": "Refuting The Lie Concerning The Excuse of Ignorance",
    "archive": "shatkh faisal pdfs/Refuting The Lie Concerning The Excuse of Ignorance.pdf",
    "size": 185755,
    "sizeLabel": "181.4 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20The%20Excuse%20of%20Ignorance.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20The%20Excuse%20of%20Ignorance.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Refuting%20The%20Lie%20Concerning%20The%20Excuse%20of%20Ignorance.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "series": "Refuting The Lie",
    "part": 2,
    "sortOrder": 7,
    "id": 7,
    "thumb": "thumb/pdfs/216157047749a7ba.jpg"
  },
  {
    "title": "100 Fabricated Hadiths (Shaikh Abdullah Faisal)",
    "archive": "shatkh faisal pdfs/100 Fabricated Hadiths (Shaikh Abdullah Faisal).pdf",
    "size": 5462038,
    "sizeLabel": "5.2 MB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/100%20Fabricated%20Hadiths%20%28Shaikh%20Abdullah%20Faisal%29.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/100%20Fabricated%20Hadiths%20%28Shaikh%20Abdullah%20Faisal%29.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/100%20Fabricated%20Hadiths%20%28Shaikh%20Abdullah%20Faisal%29.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 8,
    "id": 8,
    "thumb": "thumb/pdfs/1fcd89de9634cc98.jpg"
  },
  {
    "title": "Are You A Takfiri - Shaykh Abdullah Faisal",
    "archive": "shatkh faisal pdfs/my pdfs/Are You A Takfiri - Shaykh Abdullah Faisal.pdf",
    "size": 284584,
    "sizeLabel": "277.9 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Are%20You%20A%20Takfiri%20-%20Shaykh%20Abdullah%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Are%20You%20A%20Takfiri%20-%20Shaykh%20Abdullah%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Are%20You%20A%20Takfiri%20-%20Shaykh%20Abdullah%20Faisal.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 9,
    "id": 9,
    "thumb": "thumb/pdfs/5420953904608948.jpg"
  },
  {
    "title": "Debunking The Letter Of The Wicked Scholars To Amirul Muhmineen",
    "archive": "shatkh faisal pdfs/Debunking The Letter Of The Wicked Scholars To Amirul Muhmineen .pdf",
    "size": 414088,
    "sizeLabel": "404.4 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Debunking%20The%20Letter%20Of%20The%20Wicked%20Scholars%20To%20Amirul%20Muhmineen%20.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Debunking%20The%20Letter%20Of%20The%20Wicked%20Scholars%20To%20Amirul%20Muhmineen%20.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Debunking%20The%20Letter%20Of%20The%20Wicked%20Scholars%20To%20Amirul%20Muhmineen%20.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 10,
    "id": 10,
    "thumb": "thumb/pdfs/84883e59d0f97544.jpg"
  },
  {
    "title": "Islam the Religion of the Future by Shaykh Faisal",
    "archive": "Islam the Religion of the Future by Shaykh Faisal.pdf",
    "size": 458909,
    "sizeLabel": "448.2 KB",
    "download": "https://archive.org/download/faisalPDF/Islam%20the%20Religion%20of%20the%20Future%20by%20Shaykh%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/Islam%20the%20Religion%20of%20the%20Future%20by%20Shaykh%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/Islam%20the%20Religion%20of%20the%20Future%20by%20Shaykh%20Faisal.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 11,
    "id": 11,
    "thumb": "thumb/pdfs/2ae41500243224f5.jpg"
  },
  {
    "title": "Murjiya Refutation by shaykh faisal",
    "archive": "shatkh faisal pdfs/my pdfs/Murjiya Refutation by shaykh faisal.pdf",
    "size": 274686,
    "sizeLabel": "268.2 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Murjiya%20Refutation%20by%20shaykh%20faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Murjiya%20Refutation%20by%20shaykh%20faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Murjiya%20Refutation%20by%20shaykh%20faisal.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 12,
    "id": 12,
    "thumb": "thumb/pdfs/c61256c570bb83bb.jpg"
  },
  {
    "title": "The 7 Conditions of Shahada by Shaykh Faisal",
    "archive": "The 7 Conditions of Shahada by Shaykh Faisal.pdf",
    "size": 400906,
    "sizeLabel": "391.5 KB",
    "download": "https://archive.org/download/faisalPDF/The%207%20Conditions%20of%20Shahada%20by%20Shaykh%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/The%207%20Conditions%20of%20Shahada%20by%20Shaykh%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/The%207%20Conditions%20of%20Shahada%20by%20Shaykh%20Faisal.pdf",
    "category": "aqeedah",
    "categoryLabel": "Aqeedah & Refutations",
    "sortOrder": 13,
    "id": 13,
    "thumb": "thumb/pdfs/fadd7098aa7af237.jpg"
  },
  {
    "title": "Challenges Facing the Muslim Ummah",
    "archive": "shatkh faisal pdfs/Challenges Facing the Muslim Ummah.pdf",
    "size": 202839,
    "sizeLabel": "198.1 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "series": "Challenges Facing the Muslim Ummah",
    "part": 1,
    "sortOrder": 14,
    "id": 14,
    "thumb": "thumb/pdfs/7d10725d429f18ad.jpg"
  },
  {
    "title": "Challenges Facing the Muslim Ummah Part II",
    "archive": "shatkh faisal pdfs/Challenges Facing the Muslim Ummah Part II.pdf",
    "size": 264493,
    "sizeLabel": "258.3 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah%20Part%20II.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah%20Part%20II.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Challenges%20Facing%20the%20Muslim%20Ummah%20Part%20II.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "series": "Challenges Facing the Muslim Ummah",
    "part": 2,
    "sortOrder": 15,
    "id": 15,
    "thumb": "thumb/pdfs/aee24fa09de87c0b.jpg"
  },
  {
    "title": "Islam Under Siege By Shaykh Faisal",
    "archive": "shatkh faisal pdfs/my pdfs/Islam Under Siege By Shaykh Faisal.pdf",
    "size": 335329,
    "sizeLabel": "327.5 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Islam%20Under%20Siege%20By%20Shaykh%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Islam%20Under%20Siege%20By%20Shaykh%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Islam%20Under%20Siege%20By%20Shaykh%20Faisal.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "sortOrder": 16,
    "id": 16,
    "thumb": "thumb/pdfs/faea68c4e350eb7c.jpg"
  },
  {
    "title": "SHARIAH VS MAN-MADE LAWS by Shaykh Abdullah Faisal",
    "archive": "shatkh faisal pdfs/my pdfs/SHARIAH VS MAN-MADE LAWS by Shaykh Abdullah Faisal.pdf",
    "size": 439011,
    "sizeLabel": "428.7 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/SHARIAH%20VS%20MAN-MADE%20LAWS%20by%20Shaykh%20Abdullah%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/SHARIAH%20VS%20MAN-MADE%20LAWS%20by%20Shaykh%20Abdullah%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/SHARIAH%20VS%20MAN-MADE%20LAWS%20by%20Shaykh%20Abdullah%20Faisal.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "sortOrder": 17,
    "id": 17,
    "thumb": "thumb/pdfs/7855459d21ee158b.jpg"
  },
  {
    "title": "The Evil Rulers Of The World",
    "archive": "shatkh faisal pdfs/The Evil Rulers Of The World.pdf",
    "size": 344985,
    "sizeLabel": "336.9 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/The%20Evil%20Rulers%20Of%20The%20World.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/The%20Evil%20Rulers%20Of%20The%20World.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/The%20Evil%20Rulers%20Of%20The%20World.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "sortOrder": 18,
    "id": 18,
    "thumb": "thumb/pdfs/f0ebca2ba5dec39b.jpg"
  },
  {
    "title": "THE OBLIGATION TO ESTABLISH THE KHILAFAH by shaykh faisal",
    "archive": "shatkh faisal pdfs/my pdfs/THE OBLIGATION TO ESTABLISH THE KHILAFAH by shaykh faisal.pdf",
    "size": 242518,
    "sizeLabel": "236.8 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/THE%20OBLIGATION%20TO%20ESTABLISH%20THE%20KHILAFAH%20by%20shaykh%20faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/THE%20OBLIGATION%20TO%20ESTABLISH%20THE%20KHILAFAH%20by%20shaykh%20faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/THE%20OBLIGATION%20TO%20ESTABLISH%20THE%20KHILAFAH%20by%20shaykh%20faisal.pdf",
    "category": "ummah",
    "categoryLabel": "Ummah & Politics",
    "sortOrder": 19,
    "id": 19,
    "thumb": "thumb/pdfs/c7dc311c72b160cc.jpg"
  },
  {
    "title": "Among Your Wives and Children Are Enemies to You By Shaykh Abdullah",
    "archive": "shatkh faisal pdfs/my pdfs/Among_Your_Wives_and_Children_Are_Enemies_to_You_By_Shaykh_Abdullah.pdf",
    "size": 267321,
    "sizeLabel": "261.1 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Among_Your_Wives_and_Children_Are_Enemies_to_You_By_Shaykh_Abdullah.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Among_Your_Wives_and_Children_Are_Enemies_to_You_By_Shaykh_Abdullah.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/Among_Your_Wives_and_Children_Are_Enemies_to_You_By_Shaykh_Abdullah.pdf",
    "category": "character",
    "categoryLabel": "Character & Family",
    "sortOrder": 20,
    "id": 20,
    "thumb": "thumb/pdfs/b1e7aca68883b464.jpg"
  },
  {
    "title": "Natural Instincts - By shaykh Abdullah Faisal",
    "archive": "shatkh faisal pdfs/Natural Instincts - By shaykh Abdullah Faisal.pdf",
    "size": 13554973,
    "sizeLabel": "12.9 MB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Instincts%20-%20By%20shaykh%20Abdullah%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Instincts%20-%20By%20shaykh%20Abdullah%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Instincts%20-%20By%20shaykh%20Abdullah%20Faisal.pdf",
    "category": "character",
    "categoryLabel": "Character & Family",
    "sortOrder": 21,
    "id": 21,
    "thumb": "thumb/pdfs/272478623bd26d74.jpg"
  },
  {
    "title": "PERSONALITY DISORDERS by Shaykh Abdullah Faisal",
    "archive": "shatkh faisal pdfs/my pdfs/PERSONALITY DISORDERS by Shaykh Abdullah Faisal.pdf",
    "size": 441534,
    "sizeLabel": "431.2 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/PERSONALITY%20DISORDERS%20by%20Shaykh%20Abdullah%20Faisal.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/PERSONALITY%20DISORDERS%20by%20Shaykh%20Abdullah%20Faisal.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/my%20pdfs/PERSONALITY%20DISORDERS%20by%20Shaykh%20Abdullah%20Faisal.pdf",
    "category": "character",
    "categoryLabel": "Character & Family",
    "sortOrder": 22,
    "id": 22,
    "thumb": "thumb/pdfs/c28febf7a074c8e6.jpg"
  },
  {
    "title": "Their Hearts Are Alike",
    "archive": "shatkh faisal pdfs/Their Hearts Are Alike.pdf",
    "size": 180953,
    "sizeLabel": "176.7 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Their%20Hearts%20Are%20Alike.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Their%20Hearts%20Are%20Alike.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Their%20Hearts%20Are%20Alike.pdf",
    "category": "character",
    "categoryLabel": "Character & Family",
    "sortOrder": 23,
    "id": 23,
    "thumb": "thumb/pdfs/86bf16de006c1697.jpg"
  },
  {
    "title": "Who Are You",
    "archive": "shatkh faisal pdfs/Who Are You.pdf",
    "size": 501799,
    "sizeLabel": "490.0 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Who%20Are%20You.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Who%20Are%20You.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Who%20Are%20You.pdf",
    "category": "character",
    "categoryLabel": "Character & Family",
    "sortOrder": 24,
    "id": 24,
    "thumb": "thumb/pdfs/cb14bf43f0e6afe3.jpg"
  },
  {
    "title": "Adam and Shaitan - The eternal battle",
    "archive": "shatkh faisal pdfs/Adam and Shaitan - The eternal battle.pdf",
    "size": 325563,
    "sizeLabel": "317.9 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Adam%20and%20Shaitan%20-%20The%20eternal%20battle.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Adam%20and%20Shaitan%20-%20The%20eternal%20battle.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Adam%20and%20Shaitan%20-%20The%20eternal%20battle.pdf",
    "category": "general",
    "categoryLabel": "General",
    "sortOrder": 25,
    "id": 25,
    "thumb": "thumb/pdfs/9b88a4c64aabd379.jpg"
  },
  {
    "title": "Allah (SWT) Has Honored Bani Adam - Mankind",
    "archive": "shatkh faisal pdfs/Allah (SWT) Has Honored Bani Adam - Mankind.pdf",
    "size": 167373,
    "sizeLabel": "163.5 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Allah%20%28SWT%29%20Has%20Honored%20Bani%20Adam%20-%20Mankind.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Allah%20%28SWT%29%20Has%20Honored%20Bani%20Adam%20-%20Mankind.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Allah%20%28SWT%29%20Has%20Honored%20Bani%20Adam%20-%20Mankind.pdf",
    "category": "general",
    "categoryLabel": "General",
    "sortOrder": 26,
    "id": 26,
    "thumb": "thumb/pdfs/3f0035c542ee5ead.jpg"
  },
  {
    "title": "Natural Disasters - Why They Occur",
    "archive": "shatkh faisal pdfs/Natural Disasters - Why They Occur.pdf",
    "size": 183096,
    "sizeLabel": "178.8 KB",
    "download": "https://archive.org/download/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Disasters%20-%20Why%20They%20Occur.pdf",
    "embed": "https://archive.org/embed/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Disasters%20-%20Why%20They%20Occur.pdf#page/n1/mode/1up",
    "details": "https://archive.org/details/faisalPDF/shatkh%20faisal%20pdfs/Natural%20Disasters%20-%20Why%20They%20Occur.pdf",
    "category": "general",
    "categoryLabel": "General",
    "sortOrder": 27,
    "id": 27,
    "thumb": "thumb/pdfs/448559792f81ca5c.jpg"
  }
];
