/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './*.js',
    './data/**/*.js',
  ],
  safelist: [
    { pattern: /^(bg|text|border|ring|shadow)-(gold|slate)(\/\d+)?$/ },
    'font-semibold',
    'shadow-sm',
    'line-clamp-2',
    'line-clamp-3',
    'line-clamp-4',
    'backdrop-blur',
    'backdrop-blur-md',
    'backdrop-blur-sm',
    'shrink-0',
    'snap-start',
    'w-7',
    'w-16',
    'h-16',
    'w-14',
    'h-10',
    'w-9',
    'h-9',
    'max-h-full',
    'object-contain',
    'object-cover',
    'object-top',
    'z-[1]',
    'text-gold-light',
    'text-gold/40',
    'text-gold/50',
    'text-gold/80',
    'text-red-400/90',
    'col-span-full',
    'grid-cols-2',
    'xl:grid-cols-3',
    'xl:grid-cols-4',
    'lg:grid-cols-4',
    'sm:grid-cols-2',
    'sm:mb-4',
    'sm:p-4',
    'sm:text-sm',
    'sm:hover:-translate-y-0.5',
    'group-hover:scale-105',
    'group-hover:scale-[1.02]',
    'group-hover:text-gold',
    'group-hover:border-gold/40',
    'group-hover:bg-slate-950/35',
    'duration-300',
    'duration-700',
    'max-w-[90rem]',
    'max-w-[11.5rem]',
    'sm:w-[13rem]',
    'w-[11.5rem]',
    'min-h-[2.75rem]',
    'min-h-[3rem]',
    'min-h-[4.25rem]',
    'min-h-[12rem]',
    'opacity-40',
    'opacity-60',
    'opacity-70',
    'cursor-not-allowed',
    'cursor-pointer',
    'ring-2',
    'ring-gold',
    'shadow-lg',
    'shadow-gold/20',
    'focus:ring-1',
    'focus:ring-gold/30',
    'antialiased',
    'is-playing',
    'is-playing-audio',
    'is-ready',
    'is-done',
    'is-exiting',
    'is-entering',
    'content-swap',
    'content-swap-out',
    'content-swap-in',
    'site-page',
    'site-page-ready',
    'site-nav-pill',
    'site-nav-pill--active',
    'stagger-item',
    'page-transition-overlay',
    'page-transition-overlay--active',
  ],
  theme: {
    extend: {
      colors: {
        gold: { DEFAULT: '#d4a853', light: '#e8c97a', dark: '#b8923f' },
        slate: { 850: '#1a2332', 925: '#0c1220', 950: '#080d18' },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        gold: '0 4px 14px rgba(212, 168, 83, 0.2)',
      },
      animation: {
        'fade-up': 'fade-up 0.45s ease both',
        'fade-in': 'fade-in 0.35s ease both',
      },
      keyframes: {
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'none' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
    },
  },
};